// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Template.Migrations
{
    [DbContext(typeof(IspitDbContext))]
    [Migration("20220822155009_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Template.Models.Dostava", b =>
                {
                    b.Property<int>("DostavaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumDostave")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPrijema")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KompanijaSpojKompanijaID")
                        .HasColumnType("int");

                    b.Property<int>("TezinaPaketa")
                        .HasColumnType("int");

                    b.Property<int?>("VoziloSpojVoziloID")
                        .HasColumnType("int");

                    b.Property<int>("ZapreminaPaketa")
                        .HasColumnType("int");

                    b.HasKey("DostavaID");

                    b.HasIndex("KompanijaSpojKompanijaID");

                    b.HasIndex("VoziloSpojVoziloID");

                    b.ToTable("Dostava");
                });

            modelBuilder.Entity("Template.Models.Kompanija", b =>
                {
                    b.Property<int>("KompanijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojAngazovanja")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prihod")
                        .HasColumnType("int");

                    b.HasKey("KompanijaID");

                    b.ToTable("Kompanija");
                });

            modelBuilder.Entity("Template.Models.TipPrevoza", b =>
                {
                    b.Property<int>("TipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipID");

                    b.ToTable("TipPrevoza");
                });

            modelBuilder.Entity("Template.Models.Vozilo", b =>
                {
                    b.Property<int>("VoziloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrevozTipID")
                        .HasColumnType("int");

                    b.HasKey("VoziloID");

                    b.HasIndex("PrevozTipID");

                    b.ToTable("Vozilo");
                });

            modelBuilder.Entity("Template.Models.Dostava", b =>
                {
                    b.HasOne("Template.Models.Kompanija", "KompanijaSpoj")
                        .WithMany("Dostave")
                        .HasForeignKey("KompanijaSpojKompanijaID");

                    b.HasOne("Template.Models.Vozilo", "VoziloSpoj")
                        .WithMany("VoziloDostava")
                        .HasForeignKey("VoziloSpojVoziloID");

                    b.Navigation("KompanijaSpoj");

                    b.Navigation("VoziloSpoj");
                });

            modelBuilder.Entity("Template.Models.Vozilo", b =>
                {
                    b.HasOne("Template.Models.TipPrevoza", "Prevoz")
                        .WithMany()
                        .HasForeignKey("PrevozTipID");

                    b.Navigation("Prevoz");
                });

            modelBuilder.Entity("Template.Models.Kompanija", b =>
                {
                    b.Navigation("Dostave");
                });

            modelBuilder.Entity("Template.Models.Vozilo", b =>
                {
                    b.Navigation("VoziloDostava");
                });
#pragma warning restore 612, 618
        }
    }
}
